language: node_js
node_js:
  - "6.9.1"
cache: yarn
install:
  - yarn global add cordova ionic
  - yarn install
script:
  - ionic upload || true
before_deploy:
  - cd "$TRAVIS_BUILD_DIR/www"
deploy:
  provider: s3
  access_key_id: "$AWS_ACCESS_KEY_ID"
  secret_access_key: "$AWS_SECRET_ACCESS_KEY"
  bucket: "telstra-hackathon-agriculture.hoangpaul.com"
  skip_cleanup: true
  region: "ap-southeast-2"
